### ISSUE TITLE
Missing some drug annotations?

### ISSUE THREAD

**Issue by dnsosa** [SciBiteLabs/CORD19#1]
Hello--thanks for your hard work on this! I'm wondering if some annotations are missing? For example looking at the file: `custom_license/7817b03a433df4b3f93127feac4b0d8090c5b56c.json`

It seems that the annotation for chloroquine in this section is missing:

![image (1)](https://user-images.githubusercontent.com/7460491/77809867-eaf66e00-704e-11ea-852c-c294454f3f6b.png)

And similar missingness was observed for Kaletra in `biorxiv_medrxiv/ff54e3e961a72eb1d2500166809b3651b2f98cf6.json`

![image (2)](https://user-images.githubusercontent.com/7460491/77809903-124d3b00-704f-11ea-8fd2-ba3aa7af91db.png)

Do you know why there might be this missingness in the drug annotations in the first place? Both seem to be in the ChEMBL lexicons. Also please let me know if I'm looking in the wrong place for these annotations for some reason.

**Comment by jamesmalone** [comment]
Hey, thanks for that will look into it! (Sorry hadn't seen this earlier went into my spam folder annoyingly!)

**Comment by jamesmalone** [comment]
Good catch on this, seems the older version of the vocab was used in our tooling which was missing these two hits. We'll rerun and fix this so they're included. Thanks for the spot!

**Comment by jamesmalone** [comment]
Oli has produced a new version which addresses the missing annotations, in 1.2:
https://github.com/SciBiteLabs/CORD19/tree/master/annotated-CORD-19/1.2
