### ISSUE TITLE
chembl-id and uri - not found

### ISSUE THREAD

**Issue by hkuich** [SciBiteLabs/CORD19#10]
hello again,

thanks first of all for the awesome work. 

been working with this for a day or so and looking at the drugs, I have found that of 9636 chembl-ids annotated, 1571 are actually not found on chembl. what version of chembl were you using? Am I missing something?

here are some examples (can provide csv via email if helpful).

id | uri
-- | --
CHEMBL1628272 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1628272
CHEMBL129157 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL129157
PHRM3F14C2E1100996D4138DF1C37D6D3F54 | PHRM3F14C2E1100996D4138DF1C37D6D3F54
CHEMBL2108849 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2108849
CHEMBL1240832 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1240832
CHEMBL449118 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL449118
CHEMBL1237121 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1237121
CHEMBL2221247 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2221247
SDG01120 | SDG01120
SDG01032 | SDG01032
SDG01042 | SDG01042
GXCD1C0689EC7A9AB3A473C74E92A66E2F8 | GXCD1C0689EC7A9AB3A473C74E92A66E2F8
PHRMA52E4DD08D93455EF3837A91E8E984FD | PHRMA52E4DD08D93455EF3837A91E8E984FD
PHRMAF937BBDDD7F2A57B59A3B4B39D1C3F3 | PHRMAF937BBDDD7F2A57B59A3B4B39D1C3F3
PHRMBC6153CAEF429938486AFFD801E13515 | PHRMBC6153CAEF429938486AFFD801E13515
PHRME0AE3270572B15F3EFE184FF224CD1DA | PHRME0AE3270572B15F3EFE184FF224CD1DA
CHEMBL3542231 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL3542231
PHRM62E5846F4405B485143D9FC828193AE4 | PHRM62E5846F4405B485143D9FC828193AE4
PHRM94CBF91AA5F02A79E613CDF988818E97 | PHRM94CBF91AA5F02A79E613CDF988818E97
SDG00915 | SDG00915
SDG00876 | SDG00876
PHRMC3381CB5087C32222CDE4E2D6B480998 | PHRMC3381CB5087C32222CDE4E2D6B480998
GXCB3B11F04A4B4A8E754564A028B23B749 | GXCB3B11F04A4B4A8E754564A028B23B749
CHEMBL252929 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL252929
CHEMBL411250 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL411250
GXC165E531A379D0C9B498152F78E84698A | GXC165E531A379D0C9B498152F78E84698A
SDG00521 | SDG00521
CHEMBL2304263 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2304263
MAND60875 | MAND60875
MAND60799 | MAND60799
CHEMBL1206473 | https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL1206473
GXCA88FC67F4C3530A8DC71FC2F0344735C | GXCA88FC67F4C3530A8DC71FC2F0344735C

there are obviously also non-chembl id in here - where are they from?

**Comment by hkuich** [comment]
the same goes for roughly 300 gene symbols and hgnc, and over 1000 indications and mesh...

gene examples:

IFN1 | http://www.genenames.org/cgi-bin/gene_symbol_report?match=IFN1
-- | --
TMEM173 | http://www.genenames.org/cgi-bin/gene_symbol_report?match=TMEM173
RARRES3 | http://www.genenames.org/cgi-bin/gene_symbol_report?match=RARRES3
C18ORF54 | http://www.genenames.org/cgi-bin/gene_symbol_report?match=C18ORF54
CTGF | http://www.genenames.org/cgi-bin/gene_symbol_report?match=CTGF
C6ORF47 | http://www.genenames.org/cgi-bin/gene_symbol_report?match=C6ORF47
AARS | http://www.genenames.org/cgi-bin/gene_symbol_report?match=AARS

indications:


id | uri
-- | --
DX90099 | DX90099
SDI1246 | SDI1246
SDI0026 | SDI0026
DX90420 | DX90420
DX90250 | DX90250
DX90179 | DX90179
DX90299 | DX90299
SDI1292 | SDI1292
DX90210 | DX90210
SDI1311 | SDI1311
DX90387 | DX90387
C564356 | C564356

**Comment by jamesmalone** [comment]
Thanks, raising with the team.

**Comment by janelomax** [comment]
Hi - couple of things going on here - yes the version of ChEMBL we're using here is chembl_24 which accounts for those dead chembl ids. It takes quite a bit of effort to optimise the NER dictionaries and we're in the process of upversioning to chembl_26 now, but wanted to get this out there sooner. We'll release a new data set when it's ready.

For the others, these are entity ids we've minted ourselves because they weren't available in chembl. So anything prefixed with GXC, SDG, PHRMA or MAND is a SciBite internal id.

Same for indications - anything prefixed DX or SDI is a SciBite internal id, and the longer MeSH ids are MeSH supplementary concepts which are valid e.g. http://id.nlm.nih.gov/mesh/C564356 but looks like the URI builder isn't working for those - I'll fix that.

The gene ones I'll look into - it may be a versioning thing too.
