### ISSUE TITLE
CVprot dictionary ids do not match CVPROT#ID annotations in sentence co-occurrence

### ISSUE THREAD

**Issue by hkuich** [SciBiteLabs/CORD19#12]
The CVprot dictionary does not contain the IDs that are listed in the co-occurrence dataset. Here are the ones in the dataset:

id,uri
P59594,http://purl.uniprot.org/uniprot/P59594
P0C6X7,http://purl.uniprot.org/uniprot/P0C6X7
P59632,http://purl.uniprot.org/uniprot/P59632
P59595,http://purl.uniprot.org/uniprot/P59595
P59596,http://purl.uniprot.org/uniprot/P59596
P59637,http://purl.uniprot.org/uniprot/P59637
P0C6U8,http://purl.uniprot.org/uniprot/P0C6U8
P59634,http://purl.uniprot.org/uniprot/P59634
P59635,http://purl.uniprot.org/uniprot/P59635
P59636,http://purl.uniprot.org/uniprot/P59636
Q7TFA1,http://purl.uniprot.org/uniprot/Q7TFA1
P59633,http://purl.uniprot.org/uniprot/P59633
Q80H93,http://purl.uniprot.org/uniprot/Q80H93
Q7TFA0,http://purl.uniprot.org/uniprot/Q7TFA0
Q7TLC7,http://purl.uniprot.org/uniprot/Q7TLC7

Of course I can recover information from uniprot directly - but was this intended?

**Comment by rachhuntley** [comment]
Hello,

The proteins listed in CVPROT are from the new coronavirus strain SARS-COV2, whereas the entries you have listed above are from the older strain SARS-COV, i.e. two different proteomes.

Could you please let me know in which file you are seeing these entries and maybe send an excerpt, so we can track down where these are appearing?

Many thanks,
Rachael.

**Comment by rachhuntley** [comment]
Hello again,

We have uploaded a new version of the CVPROT file that now contains both proteomes for SARS-COV and the human targets of CV. This is based on the contents of the UniProt pre-release data (ftp://ftp.uniprot.org/pub/databases/uniprot/pre%5Frelease/).

The co-occurence dataset has also been updated using the new CVPROT data.

Many thanks,
Rachael.
