### ISSUE TITLE
Include individual cleavage products (nsp1-15) in vocabulary

### ISSUE THREAD

**Issue by cmungall** [SciBiteLabs/CORD19#14]
Our users are interested in doing searches on individual viral proteins. Termite seems to do as well as can be expected on the usual suspects like Spike. Obviously some like "M" are hard.

An important class for us are the non-structural proteins nsp1-15. These are cleavage products of polyproteins. Unfortunately UniProt does not provide individual accessions for these proteins, only for the parent polyprotein. I think that this means you still annotate mentions of these, but they get rolled up, such that it's impossible to tell hits from nsp3 from hits for nsp8 (though I'm not sure we're even getting all of these).

Being able to detect mentions of specific proteins/genes seems an important use case. I'm happy to help with building your vocabulary here. I've spent quite a lot of time looking at representations in different databases.

I recommend the protein ontology PRO as a good source here. 

You can get the obo file here:
https://proconsortium.org/download/development/pro_sars2.obo

The Wikidata representation is also good

Let me know if you have any questions, you know where to find me

**Comment by cmungall** [comment]
We are curating our vocabulary here (as a gpi file, which Jane and Rachael should be familiar with):

https://github.com/Knowledge-Graph-Hub/kg-covid-19/blob/master/curated/ORFs/uniprot_sars-cov-2.gpi

**Comment by rachhuntley** [comment]
Hi @cmungall,

We've updated our coronaprot vocab so that we are now using the Protein Ontology for the IDs. The vocab file and the annotated data made using the new vocab have been uploaded here: https://github.com/SciBiteLabs/CORD19

Let us know if you spot any further problems.

Thanks,
Rachael.

**Comment by cmungall** [comment]
Thank you!
