### ISSUE TITLE
Unexpected concept GOX000001 in annotated corpus

### ISSUE THREAD

**Issue by deepakunni3** [SciBiteLabs/CORD19#15]
Not sure where this is coming from, but what is `GOX000001`?

It was found to be associated to paper `4609a2dd3568a7241548b7303e0d836e33d4d5ca` in the `comm_use_subset` subset

**Comment by 19katz** [comment]
I ran a query to grab all the curies (in the hopes of categorizing the curies by prefix) and came up with several other similar unexpected concepts. Some examples include: 

":GXCE55A6864D57A60B12992192B40A4C958"
":MAND60348"
":PHRM17918C41E0519FE978684FB4BF6CCC07"
":HPX_000033"
":SDG00945"
":SDX00315"
":URS0000192F9C_9606"
":YU"

**Comment by TriageDr** [comment]
Attached is a file with all 1460 curies found in the covid19 kg node file that start with a colon ":"
[covid19_strange_curies.txt](https://github.com/SciBiteLabs/CORD19/files/4927704/covid19_strange_curies.txt)

**Comment by deepakunni3** [comment]
@jamesmalone The CURIEs mentioned above are the ones from SciBite's annotations. Due to lack of a label, it is unclear what these terms mean. Is there a way to reconcile the meaning of these terms? Thanks!

**Comment by janelomax** [comment]
These are internal temporary ids we mint when we feel a class is missing from the public ontology. You can always get the labels from the json, e.g.

`                    {
                        "hit_count": 1,
                        "name": "Cytotoxic T cell activation",
                        "id": "GOX000001",
                        "hit_sentences": [
                            1
                        ],
                        "hit_sentence_locations": [
                            [
                                0,
                                148
                            ]
`

**Comment by deepakunni3** [comment]
Okay, that clarifies the nature of these identifiers. Thank you @janelomax
