### ISSUE TITLE
Unable to expand CORD-19_1_1.zip / CORD-19_1_0.zip

### ISSUE THREAD

**Issue by nacharov** [SciBiteLabs/CORD19#3]
I can not open the main archives form "annotated-CORD-19" catalog. CORD-19_1_1.zip has wrong size: it is only 4 KB on my local disk. I tried to clone the repo with and download the file directly with browser. The same result. How to fix it?

Thank you.

**Comment by jamesmalone** [comment]
Hi Alexy,
I think this is because it's an LFS file. You may ned to do git lfs pull on the repo.

**Comment by jamesmalone** [comment]
Ah ok no it's because we've had our free repo bandwidth using lfs (just tried myself! OK I'll fix this.

**Comment by nacharov** [comment]
Thank you, James

**Comment by jamesmalone** [comment]
Fixed now, coughed up the £5 a month ;) You can pull now (I just tried and worked ok). Thanks for letting me know.

**Comment by nacharov** [comment]
Yes, it's works now! Thank you very match, you are doing amazing job!
