### ISSUE TITLE
CORD-19 dataset updates

### ISSUE THREAD

**Issue by Mike-Honey** [SciBiteLabs/CORD19#5]
Can you document in your readme which CORD-19 dataset version was used to produce this output?
https://www.kaggle.com/allen-institute-for-ai/CORD-19-research-challenge/discussion/137474

Looking at the dates in your current data, I presume you are at least 1 version behind right now, as v6 was dropped on 2020-04-03.  I also imagine you need time to digest the structural changes that happened in that version and re-run your processes.  Can you share your timelines for when you might publish a matching update?

**Comment by jamesmalone** [comment]
Ah yes it was the version before this. Let me see if we can get the latest set ran through the pipeline.

**Comment by jamesmalone** [comment]
@scibite-oliverg Any chance we can run this again with version 6?

**Comment by Mike-Honey** [comment]
Here's the Allen AI FAQ page, including info on the structural changes I referenced above.

https://discourse.cord-19.semanticscholar.org/t/faqs-about-cord-19-dataset/94

**Comment by jamesmalone** [comment]
Thanks Mike, Oli is going to regenerate this with the new data set (and format). More soon...

**Comment by jamesmalone** [comment]
The latest annotation using version 6 and with corrected URIs is now available from:
https://github.com/SciBiteLabs/CORD19/tree/master/annotated-CORD-19/1.3

**Comment by hkuich** [comment]
Dear James - will you be updating the "sentence-co-occurrence-CORD-19" as new literature is published/the original dataset is updated?

**Comment by jamesmalone** [comment]
Hi, Yep in fact just released a new version today with extra data set, new URI patterns and also sentence index location information for each co-occurrence. It's in version 1.1 of that folder.
