### ISSUE TITLE
Use of OBO IRIs for representing ontology terms

### ISSUE THREAD

**Issue by deepakunni3** [SciBiteLabs/CORD19#6]
@jamesmalone I am using the annotations on CORD-19 to ingest into a knowledge graph, as part of our [KG-COVID-19](https://github.com/Knowledge-Graph-Hub/kg-covid-19) efforts.

After parsing through the SciBite annotations, I noticed that most of the IRIs used for different ontology terms are malformed or don't really resolve in a browser.

Here are a few recommendations,
* `http://purl.obolibrary.org/obo/GO0003824` -> `http://purl.obolibrary.org/obo/GO_0003824`
* `https://www.ebi.ac.uk/chembl/compound/inspect/CHEMBL2074764` -> `https://www.ebi.ac.uk/chembl/compound_report_card/CHEMBL2074764`
* `http://purl.obolibrary.org/obo/HP0003198` -> `http://purl.obolibrary.org/obo/HP_0003198`
* `https://www.uniprot.org/uniprot/P0DTD1` -> `http://purl.uniprot.org/uniprot/P0DTD1`
*  `http://centree/ontology/NCBITaxon_2697049` -> `http://purl.obolibrary.org/obo/NCBITaxon_2697049` 
* `http://centree/ontology/GO_0044824` seems like an invalid IRI; Should use a PURL instead

Using these standards for representing IRI will make downstream parsing of this resource much more easy.

**Comment by jamesmalone** [comment]
Thanks Deepak. This is a consequence of the way the NER engine tags the data (it uses a short form version) and we then had to reconstruct the URIs from the short form IDs so looks like a few have slipped through. Will feed this back, cheers.

**Comment by jamesmalone** [comment]
Just to add this is being regenerated now with fixed URIs. Release coming...

**Comment by jamesmalone** [comment]
The latest annotation using version 6 and with corrected URIs is now available from:
https://github.com/SciBiteLabs/CORD19/tree/master/annotated-CORD-19/1.3

**Comment by deepakunni3** [comment]
Thank you @jamesmalone for that quick turn over 👍

**Comment by jamesmalone** [comment]
Thanks Deepak, will pass on the team! :)
