### ISSUE TITLE
git error: This repository is over its data quota

### ISSUE THREAD

**Issue by Mike-Honey** [SciBiteLabs/CORD19#8]
I'm getting this error from git:

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.

I'm not in any great rush, was just exploring the data.  Perhaps a git sample code that just extracted one file for the curious would save a lot of bandwidth?

**Comment by jamesmalone** [comment]
HI Mike,
This is resolved now (github hadn't emailed me to tell me!). Anyway set up some alerts now should be fine.
