### ISSUE TITLE
Update URIs used in dataset with entity co-occurrence

### ISSUE THREAD

**Issue by deepakunni3** [SciBiteLabs/CORD19#9]
@jamesmalone Would it be possible to update the URIs to OBO PURLs in the entity co-occurrence dataset as well (`cv19_scc.zip`)?

**Comment by jamesmalone** [comment]
Sure will speak to the team on Tuesday (note, Monday is a national holiday in the UK).

**Comment by jamesmalone** [comment]
Hi Deepak, this is now done and committed in version 1.1 of the sentence folder.

**Comment by deepakunni3** [comment]
Thank you @jamesmalone 👍
